### ISSUE TITLE
Fix issue of mixed 2.x and 3.x code: bring back 3.x code

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/mailsystem#10]
Strangely the Backdrop version of mailsystem seems to be a mix of 2.x and 3.x code. All the commits look like they were on the 3.x branch, and the `MailsystemDelegateMailSystem.inc` file is definitely 3.x, but most, if not all, of the code in mailsystem.module is from 2.x.

I propose we fix this and ensure this is all the 3.x branch code (while carrying over the fixes so it works in Backdrop).

**Comment by herbdool** [comment]
@Graham-72 I've added a PR. Looks like the original porter to Backdrop overwrote the 3.x code with older 2.x code. It's not clear why, but I suspect it was a mistake. The resulting code had a mix of 2.x functions and 3.x functions.

My PR uses the 3.x code and adds back in the changes to make it work with Backdrop. For me it's fully working, including the mixing of different mail classes to send and format (just like in Drupal 7), and it allows for the adding of custom keys.

I think the 3.x branch is superior to Mailsystem 2.x in Drupal because it doesn't require the creation of classes on the fly that have to be stored in the filesystem (which caused many issues for people in Drupal 7). Instead it saves in the config which class is being used for formatting and which for sending, for each module (+ key if needed) or globally.

Aside:
I think this is superior to hook_mailengine ultimately since it is already the accepted approach for Drupal 7 modules and doesn't rely on Mimemail. In fact, I hope we can convince others to put some of this code into Backdrop core (the structure, not the admin pages) so that we can rely on it to make settings simpler for mailing modules.

**Comment by Graham-72** [comment]
@herbdool Thank you very much for doing this. I have tried your PR on my test site and things look good, but github is showing a conflict - have you any idea what is causing this?

One concern I have is about the introduction of an option to set the 'class used to format the body of the mail'. I see from the code that this is intended for future use but it appears in the UI with no explanation. For example:
![screenshot_2018-07-29 mail system bdtest oliverhosting uk](https://user-images.githubusercontent.com/10559274/43365965-ebd76776-932c-11e8-9c7e-d2f377d3f899.png)

I am puzzling over the intention here. In what sense is it using the word 'formatting'? I presume not in the sense of formatting the HTML of an email because that is done by having a template? I think perhaps this option should be omitted until we have some further explanatory text on the page and something in the readme for the module.

Would you perhaps be interested in becoming the maintainer of this module? I think I am unlikely to be needing to use it and so don't have much incentive to deal with issues.

**Comment by herbdool** [comment]
@Graham-72 Sure, I can be the (co) maintainer if you like. Let's leave your name on it in case I can't deal with an urgent request, if that's okay.

The conflict is probably because of the previous PR you merged. It's an easy fix.

The formatting section needs to stay since it's an integral part of Mailsystem that was lost in the port. Have you used Mailsystem on Drupal 7? I'll go over the basics here on how it works in Backdrop and Drupal 7.

In `core/includes/mail.inc` it defines `MailSystemInterface` with two methods: `format` and `mail`. So every class that implements this interface need those two methods.

In `core/modules/system/system.mail.inc` it has the `DefaultMailSystem` class which implements that interface. For format it just sends plain-text emails. For mail it sends it using the server's PHP mail function. Both of these are very basic and probably won't be enough for most people since they'll want emails formatted as HTML (and maybe have attachments and images), and will need to send via SMTP (or some other API for a third-party service) so that it gets sent out properly and doesn't risk getting their domain blacklisted.

Thus, the numerous modules on Drupal 7 to deal with these two methods in different ways: formatting and sending. And this is also why they tend to rely on the Mailsystem module: so that they can mix and match modules. Use one module for formatting the email and another for sending.

For instance, in Drupal 7 HTML Mail and MimeMail are the two popular modules to deal with the formatting side. Both of them also implement the mail method but just rely on PHP's mail function which has issues (as I noted above). So this means that a popular setup is to use the SMTP module for sending (using its mail method implementation). Other popular options are PHPMailer, SendGrid, SparkPost, Postmark, etc. All of them help with the sending and leave the formatting to other modules.

Someone could in theory just write a custom module with a class that would use SMTP modules send method and HTML Mail's mail method. But Mailsystem module makes that easier by adding a bit of functionality on top of the interface and a UI for allowing the mixing and matching without having to write custom classes by hand.

I hope that helps

**Comment by Graham-72** [comment]
@herbdool Thank you for adding yourself to the maintainer list and thank you for the above explanation. However, I am still concerned by the UI, mainly because of what seems to me to be confusing terminology. I feel the meaning of the wording 'class used to format the body of the mail' is not self-evident, perhaps because the terms 'class', 'format' and 'body' each seem to be used for two or more different things in the context of mail.

Maybe we need to work towards a very carefully written user guide that explains all this and would certainly include some of what you have written above.

**Comment by herbdool** [comment]
One step at a time. I've merged this. We can create a new issue for improving the documentation and help text.
